/**
 * 代码格式化工具
 */

/**
 * 格式化配置
 */
export interface FormatConfig {
  /** 缩进大小 */
  indentSize: number;
  /** 使用空格缩进 */
  useSpaces: boolean;
  /** 最大行宽 */
  maxLineWidth: number;
}

/**
 * 默认格式化配置
 */
export const defaultFormatConfig: FormatConfig = {
  indentSize: 2,
  useSpaces: true,
  maxLineWidth: 100,
};

/**
 * 简单的代码格式化器
 */
export class CodeFormatter {
  private config: FormatConfig;

  constructor(config: Partial<FormatConfig> = {}) {
    this.config = { ...defaultFormatConfig, ...config };
  }

  /**
   * 格式化代码
   */
  format(code: string): string {
    let result = code;

    // 移除多余空行
    result = this.removeExtraBlankLines(result);

    // 修复缩进
    result = this.fixIndentation(result);

    // 移除行尾空格
    result = this.trimTrailingWhitespace(result);

    return result;
  }

  /**
   * 移除多余空行（最多保留一个连续空行）
   */
  private removeExtraBlankLines(code: string): string {
    return code.replace(/\n{3,}/g, '\n\n');
  }

  /**
   * 修复缩进
   */
  private fixIndentation(code: string): string {
    const lines = code.split('\n');
    const indentChar = this.config.useSpaces ? ' '.repeat(this.config.indentSize) : '\t';
    const result: string[] = [];

    for (const line of lines) {
      // 计算当前行的缩进级别
      const trimmed = line.trimStart();
      if (trimmed.length === 0) {
        result.push('');
        continue;
      }

      // 保持原有缩进结构，只替换缩进字符
      const leadingSpaces = line.length - trimmed.length;
      const indentLevel = Math.floor(leadingSpaces / this.config.indentSize);
      result.push(indentChar.repeat(indentLevel) + trimmed);
    }

    return result.join('\n');
  }

  /**
   * 移除行尾空格
   */
  private trimTrailingWhitespace(code: string): string {
    return code
      .split('\n')
      .map((line) => line.trimEnd())
      .join('\n');
  }

  /**
   * 添加文件头注释
   */
  addFileHeader(code: string, comment: string): string {
    const header = this.formatComment(comment);
    return header + '\n\n' + code;
  }

  /**
   * 格式化注释
   */
  private formatComment(comment: string): string {
    const lines = comment.split('\n');
    if (lines.length === 1) {
      return `// ${comment}`;
    }

    const formattedLines = lines.map((line) => ` * ${line}`);
    return ['/**', ...formattedLines, ' */'].join('\n');
  }
}

/**
 * 简单的代码美化（不依赖外部库）
 */
export function beautifyCode(code: string, config?: Partial<FormatConfig>): string {
  const formatter = new CodeFormatter(config);
  return formatter.format(code);
}

/**
 * 添加自动生成的文件头
 */
export function addGeneratedHeader(code: string, platform: string): string {
  const timestamp = new Date().toISOString();
  const header = `// Generated by Pixso CodeForge
// Platform: ${platform}
// Generated at: ${timestamp}
// Do not edit manually
`;
  return header + '\n' + code;
}
